### ISSUE TITLE
VS 2017 'GetObject' is not a member of 'IObjectFactorySystem'

### ISSUE THREAD

**Issue by 1JQ** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#102]
Hello! I was having problems I added this to my project and compiled (After repairing error that I had Project compiled but runtime compilation doesn't seem to be working) a few months ago. 
Now I returned to this, I've made class for single file Runtime Compiling that has all necessary code form ConsoleExample and I have new problems...
-error from the title
-I installed everything that I found for visual studio 2012 (that people in internet suggested to install) and I still had error that I don't have build tools (for VS 2012), so I've done that what VS was suggesting (used 'retaget project'). I am saying this because maybe that was a wrong move.

I am using:
-SFML (I will maybe move to clean OpenGl in the future)

**Comment by dougbinks** [comment]
Re-targeting the project was the right thing to do. SFML shouldn't be an issue (I use GLFW which serves a similar purpose).

I'm not sure what your exact error is - could you post the text from the output during compile?

As you can see from the header, [GetObject() is a member of IObjectFactorySystem](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/blob/master/Aurora/RuntimeObjectSystem/IObjectFactorySystem.h#L44), so I need some more details to figure out what's going on.

**Comment by 1JQ** [comment]
Output (build):
1>s:\sfml classes\jqclassses\jqruntimedebugger.h(81): error C2039: 'GetObject': is not a member of 'IObjectFactorySystem'
1>s:\sfml classes project\runtimeobjectsystem\runtimeobjectsystem.h(42): note: see declaration of 'IObjectFactorySystem'
1>s:\sfml classes\jqclassses\jqruntimedebugger.h(125): error C2039: 'GetObject': is not a member of 'IObjectFactorySystem'
1>s:\sfml classes project\runtimeobjectsystem\runtimeobjectsystem.h(42): note: see declaration of 'IObjectFactorySystem'

Note: Before compiling I see also this error on word "GetObject".

Note nr 2: In IObjectFactorySystem.h GetObject function is other color than others and when cursor is on it VS says:  
"#define GetObject GetObjectW
Expands to: GetObjectW"

**Comment by dougbinks** [comment]
This is because something is including Windows.h which is defining GetObject as a macro.

You can potentially fix this by moving the includes for Runtime Compiled C++ above whatever include is including Windows.h.

If that doesn't fix it, you might be able to ensure you can ```#undef GetObject``` after the include which is including Windows.h and this may work so long as you don't need the windows function GetObject.

**Comment by dougbinks** [comment]
I'm going to close this issue as I've not heard back and it appears to be not directly related to an issue in RCC++.

**Comment by 1JQ** [comment]
Thanks! That fixed it! I've had some errors when I tried to include that runtime class to my project (first the m_pRuntimeObjectSystem was nullptr, then when I tried to copy ConsoleExample project settings 1 to 1 I've had 0 constructors error when m_pRuntimeObjectSystem was initialized). So I tried to edit Aurora, remove useless projects and all useless and runtime files, add my class and now it works!

**Comment by 1JQ** [comment]
Sorry, for late comment (I wanted to post this upper comment 6 hours ago) but I didn't have to much time.

**Comment by dougbinks** [comment]
Glad to hear you've got things working!
