### ISSUE TITLE
Question: Use Case: Self-optimization

### ISSUE THREAD

**Issue by f-tischler** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#107]
Hi,

I stumbled across your project while looking for a way to compile optimized code depending on runtime input. From what I've seen, it's a great project, especially because it is cross-platform.

Since you mention that this (runtime compilation in production) is not the main application scenario, I am curious if you think that RuntimeCompiledCPlusPlus is something that would work well in this case nevertheless.

The application runs on our own machines so we can ensure that all required build tools are available so this won't be a problem. 

Best,
Florian

**Comment by dougbinks** [comment]
If you control the machines so can ensure all required build tools are available then it's plausible that this might work for you.

There are some caveats - at the moment RCC++ doesn't unload the the shared libraries produced from compiling previous code so there is effectively a potential memory leak over time. I could add code to permit unloading of any unreferenced libraries if this might pose an issue.

**Comment by f-tischler** [comment]
Thanks for your fast response.

Yes, I read that, but actually I would be fine with restarting the application if that becomes a problem. However, this leads me to another question: does it recompile if there are no changes between application starts?

**Comment by dougbinks** [comment]
The current automatic recompilation behaviour is dependent on a file change during execution of the program, however you can force recompilation with IRuntimeObjectSystem::CompileAllInProject().

**Comment by f-tischler** [comment]
I assume thatIRuntimeObjectSystem::CompileAllInProject() works even if automatic recompilation is disabled.

Based on that, compilation is only triggered when
- explicitly instructed to by using IRuntimeObjectSystem::CompileAllInProject()
- when it detects file changes while running

it does not automatically recompile
- on application startup (event if files changed while the program was not running)
 
Did I get that right?

**Comment by dougbinks** [comment]
Apologies for the late response, I somehow did not see the new reply.

Yes, that's correct - the primary use case for RCC++ is for changes during the running of the application.

I could add support for compiling files which are newer than the base exe on startup via a CompileAllNewFilesProject() function or similar if needed.

**Comment by dougbinks** [comment]
I'm closing this question as I think this has been answered now.
