### ISSUE TITLE
RUNTIME_COMPILER_SOURCEDEPENDENCY off-by-1 error

### ISSUE THREAD

**Issue by machacekch** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#111]
On VS2019 the demo at https://github.com/juliettef/RCCpp-DearImGui-GLFW-example fails to build at runtime, because imgui/imgui_demo isn't linked. As a workaround, one can duplicate RCCppMainLoop.cpp#17:
RUNTIME_COMPILER_SOURCEDEPENDENCY_FILE( "imgui/imgui_demo", ".cpp" );
to make it compile successfully.

It seems like a81c8fd3ec6f454b4eb31f2deee89d14b32a33a8 introduced an off-by-1 error where the last RUNTIME_COMPILER_SOURCEDEPENDENCY_FILE has no effect.

(Note that the other example at https://github.com/dougbinks/RCCpp_DX11_Example is unaffected, because it references an older version of RCCpp, which doesn't have the commit mentioned above.)

**Comment by dougbinks** [comment]
Thanks for the report - I'll take a look at this shortly!

**Comment by dougbinks** [comment]
Once again thanks for the report - as you predicted I had an off by one error in one function call.

Oddly my own code and tests didn't trigger this.
