### ISSUE TITLE
Stack Cookie Check Failure error

### ISSUE THREAD

**Issue by nikhilghosh75** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#117]
I'm trying to use RuntimeCompiledCPlusPlus in my own game engine and I'm having a very strange error. I've created a main loop class that looks like this:

RUNTIME_COMPILER_SOURCEDEPENDENCY;

struct RCCppMainLoop : IRCCppMainLoop, TInterface<IID_ENDInterfaceID, IObject>
{
	RCCppMainLoop()
	{
		PerModuleInterface::g_pSystemTable->mainLoop = this;
		std::cout << "New Main Loop Constructed" << std::endl;
	}

	virtual void MainLoop() override
	{
		std::cout << "TEST 1" << std::endl;
	}
};

REGISTERSINGLETON(RCCppMainLoop, true);

The system table has a pointer to this main loop class. I ran this code in a Debug configuration in Visual Studio 2017 on Windows, and I got an exception in gs_report.c that says "Stack cookie instrumentation code detected a stack-based buffer overrun." Looking at the call stack, it seems to occur in the REGISTERSINGLETON macro when constructing the TObjectConstructorConcrete class.  Looking at the memory section of visual studio, it seems like the m_pRuntimeTrackingList vector is null.

What can I do to fix this, if anything? Thank you in advance for the help!

**Comment by dougbinks** [comment]
The first thing I've noted is that you have added:

```RUNTIME_COMPILER_SOURCEDEPENDENCY```

This is only needed if you're not using ```REGISTERSINGLETON``` in that file. I'll add that to the documentation, so you should remove it.

I presume you've been able to get the sample https://github.com/juliettef/RCCpp-DearImGui-GLFW-example (or the DX version) running fine?
