### ISSUE TITLE
Dynamic loading of generated code without writing to files

### ISSUE THREAD

**Issue by xbotuk** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#118]
Is it possible to dynamic loading of newly generated code or modification of existing code, from String without using file system?

**Comment by dougbinks** [comment]
This is not possible without the file system as RCC++ uses an installed compiler, and these use the file system for compiling.

The SimpleTest (Pulse) example has a console which writes a string out to a file to compile it.
https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/blob/master/Aurora/Examples/SimpleTest/Console.cpp#L570-L588

This uses ```RuntimeObjectSystem::AddToRuntimeFileList``` to add the file for runtime compilation, then writes to it as required triggering compilation.

**Comment by dougbinks** [comment]
Closing as answered. Please re-open if you have further questions on this particular issue.
