### ISSUE TITLE
Runtime Linker issues

### ISSUE THREAD

**Issue by Platforming-Mayhem** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#126]
Hi, 
I am having an issue with the runtime compiler and ImGui. ImGui keeps spitting out Linker errors after I recompile the RCCppMain.cpp
![image](https://user-images.githubusercontent.com/82027284/232162140-61d259be-1e29-4c83-847b-ccdba8b692d4.png)
![image](https://user-images.githubusercontent.com/82027284/232162179-e258fe42-7a13-4814-8412-4b966cc98767.png)
I would really appreciate some help to solve this issue
Thanks

**Comment by RuntimeCompiledCPlusPlus** [comment]
I am out and will be unable to respond properly for some time. I would
check the wiki on the RCC++ wiki. It looks like the source files for these
functiins may not have the runtime source dependency set (
RUNTIME_COMPILER_SOURCEDEPENDENCY_FILE). If you look in the Dear ImGui
example code and article you can see how this works
https://www.enkisoftware.com/devlogpost-20200202-1-Runtime-Compiled-C++-Dear-ImGui-and-DirectX11-Tutorial

If you have updated Dear ImGui to a new version from the ine in the
tutorial there may be more files which need to be added.

**Comment by Platforming-Mayhem** [comment]
Do you know how to link to source files that aren't in the same directory as the RCCppMainloop.cpp?

**Comment by dougbinks** [comment]
The path you should use is the relative path from the file where you have the `RUNTIME_COMPILER_SOURCEDEPENDENCY_FILE` macro.

So for example if you have the following structure:

```
E:\K-Engine\vendors\imgui\imgui.cpp
... etc.
E:\K-Engine\Application\RCCppMainloop.cpp
```

Then you should use:
`RUNTIME_COMPILER_SOURCEDEPENDENCY_FILE("../vendors/imgui/imgui", ".cpp");`

Where `..` means the directory below the directory of the current file.

**Comment by Platforming-Mayhem** [comment]
Thanks, but I still seem to get linker errors:
![image](https://user-images.githubusercontent.com/82027284/232319550-f39dde0b-9784-49fd-b18f-57797bea71e6.png)

**Comment by dougbinks** [comment]
You need to add all the Dear ImGui files which you are compiling using the `RUNTIME_COMPILER_SOURCEDEPENDENCY_FILE` macro. If you have updated Dear ImGui this means you may have different files to those in the original tutorial.

Do you have a list of the Dear ImGui files you have added to your project?

**Comment by dougbinks** [comment]
Looking at the latest version of Dear ImGui I can see that you need to add `imgui_tables.cpp` which is a new file added after the Tutorial was made.

**Comment by Platforming-Mayhem** [comment]
Thank youuuuu! It worked :)
