### ISSUE TITLE
Runtime Compiled C++ Linker Errors

### ISSUE THREAD

**Issue by Platforming-Mayhem** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#128]
![image](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/assets/82027284/ad3f0b46-004a-4930-af78-1b734430dfec)
My game engine is compiled into a single DLL and I specify DLLexport and import using Macros.
![image](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/assets/82027284/642a258e-623a-4613-8cf6-f1171526464b)
I think it might be failing to compile because of that?

**Comment by dougbinks** [comment]
I would recommend having a thorough read of the [RCC++ documentation in the wiki](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/wiki).

In particular [Using libraries from runtime modifiable classes](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/wiki/Using-libraries-from-runtime-modifiable-classes).

By the looks you will likely need to link to the engine dll itself along with GLEW.

Given your recent questions I think it might be that you are undertaking too large a project as your first project with RCC++. It might help to first undertake a smaller demo project and then build up from there.

Note that it's difficult to understand text in the format of images, and I can't copy paste to do search or make tests etc.. It would be much easier if you could paste in the text output if possible in future.

**Comment by Platforming-Mayhem** [comment]
Alright, will do, thanks :)
