### ISSUE TITLE
Missing whitespace when concatenating additional copiler and link options

### ISSUE THREAD

**Issue by kubaroth** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#48]
The error can be circumvented by adding one extra space to a string passed to SetAdditionalCompileOptions().

**Comment by dougbinks** [comment]
I've fixed this on the development repo at https://github.com/dougbinks/RuntimeCompiledCPlusPlus/commit/f925bfd908c93515f6dc982213a0e8e65047ce64 and will merge this with some other work once I've completed a few tests, hopefully today.

**Comment by dougbinks** [comment]
This should now be fixed.
