### ISSUE TITLE
QtCreator

### ISSUE THREAD

**Issue by inter1965** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#49]
It would be nice to support QtCreator.

**Comment by dougbinks** [comment]
The code should work with QtCreator, but I don't ship a project configuration for it at the moment. The Cmake files might work for Linux & Mac OS X QtCreator. I'll take a look at this at some point though to check.

**Comment by dougbinks** [comment]
You can now open the CMakeLists.txt file in the Aurora directory to generate a QtCreator project. Make sure cmake is installed and on Windows the path to cmake is set in QtCreator->Tools->options->CMake
