### ISSUE TITLE
Tutorial 01 doesn't work with VS2013 with CMake

### ISSUE THREAD

**Issue by dtmoodie** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#50]
Hello,

I just built used CMake to build this project with VS2013.  Everything compiles fine but changing my source file changes nothing in the program.  I'd like to know where I should look into this.
I'll try compiling and running with GCC later today.

**Comment by dougbinks** [comment]
CMake for Visual Studio currently doesn't work - please use the Visual Studio solutions provided.

I will at some point fix up the cmake files, but since I provide a VS solution it's low priority.

**Comment by dtmoodie** [comment]
Thank you, my apologies if that was listed somewhere.  My plan is to integrate this into a library I'm building for image processing.  I currently use CMake for that library, so I guess for now I'll be stuck developing it on Linux.
I got it working with the visual studio solution and I have to say it's quite fantastic, I look forward to CMake support with visual studio.

Any idea if something like this would be possible with cuda code as well?

**Comment by dougbinks** [comment]
The changes needed to cmake should be fairly simple, so I'll see if I can
have a go.

Runtime compilation of cuda is certainly possible, but it's outside the
domain of this project.

**Comment by dtmoodie** [comment]
Once more thanks a ton.  If I can get this working with my project, I'll definitely look into expanding it with runtime cuda compilation.

**Comment by dougbinks** [comment]
VIsual Studio should now work fine from cmake, but let me know if you find further issues.
