### ISSUE TITLE
Linking error. Bug?

### ISSUE THREAD

**Issue by ColinGilbert** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#62]
Hi, I adapted the console example and received this error:

```
/usr/local/lib64/libRuntimeCompiler.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
```
The rest of the program compiles and links fine.

**Comment by ColinGilbert** [comment]
Hmm. Reinstalling the libs solved the problem.

**Comment by dougbinks** [comment]
Glad you managed to resolve that!
