### ISSUE TITLE
RCPP crashes on start.

### ISSUE THREAD

**Issue by ColinGilbert** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#63]
Hi, 

I have written some code modeled upon the ConsoleExample, but it crashes upon start when calling any of the runtime-compilable functions. I have made a repro; could someone tell me if I am appropriately using this library?

https://github.com/ColinGilbert/rcpp-repro.git

**Comment by dougbinks** [comment]
The initialization looks reasonable - could you tell me where this crashes and perhaps include any debugger information (callstack etc.)?

**Comment by dougbinks** [comment]
I've not heard back about this so am closing.
