### ISSUE TITLE
Investigate retaining object files for Posix compilers

### ISSUE THREAD

**Issue by dougbinks** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#65]
Currently the posix compiler system doesn't retain intermediate object files, which could slow down runtime compile times. Investigate and add this feature if it helps.

**Comment by procedural** [comment]
Thanks for opening this feature request, Doug!

Can you show where RCC++ includes `ObjectInterfacePerModuleSource.cpp` so I could try to manage its compiling myself?

**Comment by dougbinks** [comment]
That file is added via the `GetRequiredSourceFiles` interface, through `AddRequiredSourceFiles` function. I will probably soon depreciate this functionality in favour of the `RUNTIME_COMPILER_SOURCEDEPENDENCY` approach ( a newer and cleaner general method).

However this is not specific to that file, there is a `BuildTool` interface which works well on Windows and with the correct compile changes to `Compiler_PlatformPosix` this should pick up the object files and use those.

**Comment by procedural** [comment]
Now I'm passing object file myself and the change is substantial: before it compiled two files, now only one -- it's twice as fast now

**Comment by dougbinks** [comment]
I've now done a generic fix which should speed up compiles in https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/commit/4a484c8d350148cde68c3c7bf8fcaad1af111d5d

**Comment by procedural** [comment]
@dougbinks it changes directory for compiling now, but compile inputs doesn't account for `cd` command and paths become incorrect:

```
Serializing out from 0 old constructors...
Swapping in and creating objects for 1 new constructors...
Serialising in...
Auto Constructing Singletons...
Initialising and testing new serialisation...
Object swap completed
Compiling...
cd "/mnt/space/OF Projects/ofLiveApp/build/Runtime/RELEASE_PERF"
clang++  -g -fPIC -fvisibility=hidden -shared -Os  --save-temps -I"../RuntimeCompiledCPlusPlus/Aurora/RuntimeObjectSystem" -I"../RuntimeCompiledCPlusPlus/Aurora/RuntimeCompiler" -I"/usr/include/AL" -I"/usr/include/cairo" -I"/usr/include/gtk-3.0" -I"/usr/include/atk-1.0" -I"/usr/include/glib-2.0" -I"/usr/include/harfbuzz" -I"/usr/include/pixman-1" -I"/usr/include/libpng12" -I"/usr/include/pango-1.0" -I"/usr/include/freetype2" -I"/usr/include/gio-unix-2.0" -I"/usr/include/gstreamer-1.0" -I"/usr/include/gdk-pixbuf-2.0" -I"/usr/include/at-spi2-atk/2.0" -I"/usr/lib/x86_64-linux-gnu/glib-2.0/include" -I"../../../../of/src/openframeworks" -I"../../../../of/src/openframeworks/3d" -I"../../../../of/src/openframeworks/app" -I"../../../../of/src/openframeworks/communication" -I"../../../../of/src/openframeworks/events" -I"../../../../of/src/openframeworks/gl" -I"../../../../of/src/openframeworks/graphics" -I"../../../../of/src/openframeworks/math" -I"../../../../of/src/openframeworks/sound" -I"../../../../of/src/openframeworks/types" -I"../../../../of/src/openframeworks/utils" -I"../../../../of/src/openframeworks/video" -I"../../../../of/src/freeimage" -I"../../../../of/src/freeimage/OpenEXR" -I"../../../../of/src/freeimage/OpenEXR/Half" -I"../../../../of/src/freeimage/OpenEXR/Iex" -I"../../../../of/src/freeimage/OpenEXR/IlmImf" -I"../../../../of/src/freeimage/OpenEXR/IlmThread" -I"../../../../of/src/freeimage/OpenEXR/Imath" -I"../../../../of/src/glew" -I"../../../../of/src/glew/include" -I"../../../../of/src/glfw" -I"../../../../of/src/glfw/include" -I"../../../../of/src/glfw/include/GLFW" -I"../../../../of/src/kissfft" -I"../../../../of/src/kissfft/tools" -I"../../../../of/src/libtess2" -I"../../../../of/src/libtess2/Include" -I"../../../../of/src/libtess2/Source" -I"../../../../of/src/poco" -I"../../../../of/src/poco/Crypto/include" -I"../../../../of/src/poco/Foundation/include" -I"../../../../of/src/poco/Net/include" -I"../../../../of/src/poco/NetSSL_OpenSSL/include" -I"../../../../of/src/poco/Util/include" -I"../../../../of/src/poco/XML/include" -I"../../../../of/src/poco/Zip/include" -I"../../../../of/src/rtaudio" -I"../../../../of/src/rtaudio/include" -I"../../../../of/src/utf8cpp" -I"../../../../of/src/utf8cpp/include" -I"../../../RuntimeCompiledCPlusPlus/Aurora" -I"../../.." -L"../../../../of/lib-linux/release" -F"../../../../of/lib-linux/release" -include ../../cotire/ofApp_CXX_prefix.hxx "../src/ofApp.cpp" "../RuntimeCompiledCPlusPlus/Aurora/RuntimeObjectSystem/ObjectInterfacePerModuleSource.cpp"  -DRCCPP -DOF_USING_GTK -DOF_USING_MPG123 -DOF_SOUND_PLAYER_OPENAL -DOF_SOUNDSTREAM_RTAUDIO -DOF_VIDEO_PLAYER_GSTREAMER -DOF_VIDEO_CAPTURE_GSTREAMER -Wno-switch -Wno-c++11-narrowing -Wno-ignored-attributes -Wno-deprecated-register -std=gnu++11 -lPocoFoundation -lassimp -lfreeimage -lglew -lglfw -lkissfft -lopenFrameworks -lPocoCrypto -lPocoJSON -lPocoNet -lPocoNetSSL -lPocoUtil -lPocoXML -lrtaudio -ltess2 -lboost_filesystem -lboost_system -lrt -ldl -lXi -lSM -lICE -lX11 -lXext -lXrandr -lXcursor -lXxf86vm -lXinerama -ludev -lgtk-3 -lgdk-3 -latk-1.0 -lgio-2.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lpango-1.0 -lcairo -lgobject-2.0 -lglib-2.0 -lglib-2.0 -lgthread-2.0 -lgmodule-2.0 -lz -lasound -lopenal -lcairo -lGLU -lGL -lSM -lICE -lX11 -lXext -lssl -lcrypto -lsndfile -lfreetype -lgstreamer-1.0 -lfontconfig -lpthread -lgstapp-1.0 -lgstbase-1.0 -lgstvideo-1.0  
 mv "/mnt/space/OF Projects/ofLiveApp/build/Runtime/RELEASE_PERF/a.out" "/tmp/RCCppTempDylibdedUxL"


clang: error: no such file or directory: '../src/ofApp.cpp'
clang: error: no such file or directory: '../RuntimeCompiledCPlusPlus/Aurora/
```

If I temporary remove `cd` and compile in `build` directory as before, it works fine:

```patch
--- a/Aurora/RuntimeCompiler/Compiler_PlatformPosix.cpp
+++ b/Aurora/RuntimeCompiler/Compiler_PlatformPosix.cpp
@@ -227,8 +227,8 @@
 	if( compilerOptions_.intermediatePath.Exists() )
 	{
 		// add save object files
-        compileString = "cd \"" + compilerOptions_.intermediatePath.m_string + "\"\n" + compileString + " --save-temps ";
-		output = compilerOptions_.intermediatePath / "a.out";
+		compileString = compileString + " --save-temps ";
+		output = "a.out";
 		bCopyOutput = true;
 	}
 ```

Except with changes of https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/commit/4a484c8d350148cde68c3c7bf8fcaad1af111d5d compile time is now takes 10 seconds instead of 5 before it.

**Comment by dougbinks** [comment]
The compile inputs should be made absolute, you could do this with 'FileSystemUtils::GetCurrentPath()' or using the guidance in the wiki: https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/wiki/Specifying-include-directories

**Comment by procedural** [comment]
@dougbinks yea, but compile inputs are not the problem here, I have no control over inclusion of `ObjectInterfacePerModuleSource.cpp` and `ofApp.cpp` compile flags, they're generated by RCC++ and their paths are relative and incorrect right now

**Comment by dougbinks** [comment]
Ah - you need to set the define 'case set the define COMPILE_PATH="$(PWD)/";' as per https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/wiki/Integrating-to-your-own-codebase since '__FILE__' on gcc is relative (with no control, and that's a pain).

**Comment by dougbinks** [comment]
I've updated the cmake files with this define, see https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/pull/77

On my system cmake was generating builds with the full path in already, and gcc / clang define __FILE__ as the path supplied to the compiler. Hence it wasn't generating any bugs on my tests.

**Comment by procedural** [comment]
@dougbinks I'll give it a try, thanks!

**Comment by procedural** [comment]
@dougbinks yeah, I got it working, but honestly I don't know why its taking 10 seconds now to compile what's took 5 before...

**Comment by procedural** [comment]
Wait, no, it's 5 seconds again, yaaay... It's 10 seconds if I use precompiled header. That doesn't make sense. At least with [forked](https://github.com/ofnode/RuntimeCompiledCPlusPlus) old version I get 2-3 seconds with PCH.

**Comment by procedural** [comment]
And I've noticed that RCC++ uses object file `Runtime/RELEASE_PERF/ofApp.o` for a file that I'm trying to change, that doesn't make sense either...

**Comment by dougbinks** [comment]
The build system will start without any object files, so will take slightly
longer on first build. It should then be faster. It detects changed files
and forces those to be recompiled rather than using object files - if
that's not working it's a serious bug I need to investigate.

Why you're getting slower compiles I don't know - on several machines this
improved compile times for me by around 2x. Potentially disk speed is an
issue here - so far I've only tested with SSDs.

When I get time I'll take a look at your project and investigate, but this
may not be for a few days.

**Comment by procedural** [comment]
> Potentially disk speed is an
issue here - so far I've only tested with SSDs.

Oh, yeah, right, I'm using HDD on notebook which can be pretty slow (5400 RPM)

**Comment by dougbinks** [comment]
I'll do some disk tests when I get time, and consider an alternative
approach if needed.
