### ISSUE TITLE
Visual Studio 2015 sporadically fails to compile runtime code changes

### ISSUE THREAD

**Issue by dougbinks** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#78]
From time to time I get the compile error:

fatal error C1902: Program database manager mismatch; please check your installation

Removing the recently added fastlink option fixes this.

**Comment by dtmoodie** [comment]
Is this a valid link option with vs2013?  I use the 2015 IDE but 2013 compiler and RCC keeps throwing errors with that flag.  Should it be >= 1900?

**Comment by dougbinks** [comment]
Yes, that's correct. Will fix.
