### ISSUE TITLE
Visual Studio 2017: compiler tools cannot be found

### ISSUE THREAD

**Issue by Naeron1984** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#89]
See:
https://blogs.msdn.microsoft.com/vcblog/2016/10/07/compiler-tools-layout-in-visual-studio-15/

Because of that, there is no registry key anymore to query so RCC++ cannot find the compiler tools.

As a workaround, I hard-coded the path but obviously, that's not the solution.

**Comment by dougbinks** [comment]
At first glance this looks like a nightmare to resolve, so a fix may be some time in coming.

**Comment by dougbinks** [comment]
This should hopefully fix things, though I note that MS claim that the key I'm using is not guaranteed to remain present. However hopefully by then there will be an easier solution that the one they propose in their sample code.

**Comment by Naeron1984** [comment]
Wow, very quick response! Thanks!
