### ISSUE TITLE
Failed to load module (fatal error C1041: cannot open program database '...\vc140.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS)

### ISSUE THREAD

**Issue by Naeron1984** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#91]
The issue only happens after a bug was introduced (tutorial 2) and fixed OR after the execution of the program was paused by a breakpoint.

I disabled Edit and Continue but did not help. Also, I have observed that devenv.exe holds **vc140.pdb**.

/FS flag is set for all the projects for AOT compilation (not sure if that has any effect) and also SetAdditionalCompileOptions("/FS", 0); is called at the beginning of the program.

Environment: Windows 10, VS2017, both Win32 and x64.

I will try to reproduce it on my other computer and report back later.

**Comment by dougbinks** [comment]
I've not experienced this, as the /Fe"path" option is used which sets the dll name and also appears to set the pdb name (though the documentation is not exact on this). I can add /Fd  to the windows compiler code to specify the pdb file if you find this still occurs.

**Comment by Naeron1984** [comment]
I'm confused. Isn't it true that If RCC++ modifies the program in the memory, the pdb file should reflect that? So if the debugger is used in VS then the breakpoints will work correctly. So VS and RCC++ should use the same pdb file? I'm a C#/JS developer with minimal C++ experience so that is how I understand it 
but I can easily be wrong.

So what you mean is that I should use the /Fe option anyway and see if it works or not?

**Comment by dougbinks** [comment]
When code is changed RCC++ writes out a dll (and a pdb) to [the temp directory with a random name](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/blob/72501484420a5a35dc9833fe2cf5320ef58326ed/Aurora/RuntimeObjectSystem/RuntimeObjectSystem.cpp#L268-L273). This dll is loaded by RCC++ and if a debugger is attached it will load the pdb and be able to set breakpoints correctly.

You don't need to set /Fe [as this is already set by RCC++](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/blob/72501484420a5a35dc9833fe2cf5320ef58326ed/Aurora/RuntimeCompiler/Compiler_PlatformWindows.cpp#L412).

If you continue to get problems, could you paste the text of the log output or what you get in the debugger output window? If RCC++ is outputting pdbs with the same name on some systems I'll need to add /Fd to set the pdb name manually.

**Comment by Naeron1984** [comment]
I can reproduce the issue every time. Here is the log from the VS Output from the point of introducing the BUG in Tutorial 2. Then I hit continue and fixed the bug and saved the file.

```
FileChangeNotifier triggered recompile with changes to:
    File c:\deepui_2017\runtimecompiledcplusplus-master\aurora\examples\simpletest\gameobject.cpp
Compiling...
cl /nologo /Zi /FC /MDd /LDd /Od /FS /D UNICODE /D _UNICODE  /MP /Fo"C:\DeepUI_2017\RuntimeCompiledCPlusPlus-master\Aurora\x64\Debug\Runtime\DEBUG_DEBUG\\" /D WIN32 /EHa /FeC:\Users\Naeron\AppData\Local\Temp\FAD9.tmp  /I "c:\deepui_2017\runtimecompiledcplusplus-master\aurora\runtimeobjectsystem" /I "c:\deepui_2017\runtimecompiledcplusplus-master\aurora\RuntimeCompiler"  "c:\deepui_2017\runtimecompiledcplusplus-master\aurora\examples\simpletest\gameobject.cpp" "c:\deepui_2017\runtimecompiledcplusplus-master\aurora\x64\debug\runtime\debug_debug\objectinterfacepermodulesource.obj" /link /DEBUG:FASTLINK 
echo 
Microsoft Windows [Version 10.0.14393]

(c) 2016 Microsoft Corporation. All rights reserved.

C:\DeepUI_2017\RuntimeCompiledCPlusPlus-master\Aurora\x64\Debug>

**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26403.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'

gameobject.cpp
   Creating library C:\Users\Naeron\AppData\Local\Temp\FAD9.lib and object C:\Users\Naeron\AppData\Local\Temp\FAD9.exp
The thread 0x3548 has exited with code 0 (0x0).

[RuntimeCompiler] Complete

'SimpleTest.exe' (Win32): Loaded 'C:\Users\Naeron\AppData\Local\Temp\FAD9.tmp'. Symbols loaded.
Compilation Succeeded
Serializing out from 48 old constructors...
Swapping in and creating objects for 1 new constructors...
Serialising in...
Auto Constructing Singletons...
Initialising and testing new serialisation...
Object swap completed
Compile and Module Reload Time: 2.3 s
Have caught an exception in main entity Update loop, code will not be run until new compile - please fix.
FileChangeNotifier triggered recompile with changes to:
    File c:\deepui_2017\runtimecompiledcplusplus-master\aurora\examples\simpletest\gameobject.cpp
Compiling...
cl /nologo /Zi /FC /MDd /LDd /Od /FS /D UNICODE /D _UNICODE  /MP /Fo"C:\DeepUI_2017\RuntimeCompiledCPlusPlus-master\Aurora\x64\Debug\Runtime\DEBUG_DEBUG\\" /D WIN32 /EHa /FeC:\Users\Naeron\AppData\Local\Temp\728B.tmp  /I "c:\deepui_2017\runtimecompiledcplusplus-master\aurora\runtimeobjectsystem" /I "c:\deepui_2017\runtimecompiledcplusplus-master\aurora\RuntimeCompiler"  "c:\deepui_2017\runtimecompiledcplusplus-master\aurora\examples\simpletest\gameobject.cpp" "c:\deepui_2017\runtimecompiledcplusplus-master\aurora\x64\debug\runtime\debug_debug\objectinterfacepermodulesource.obj" /link /DEBUG:FASTLINK 
echo 
Microsoft Windows [Version 10.0.14393]

(c) 2016 Microsoft Corporation. All rights reserved.

C:\DeepUI_2017\RuntimeCompiledCPlusPlus-master\Aurora\x64\Debug>

**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26403.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'

gameobject.cpp
The thread 0x211c has exited with code 0 (0x0).
c:\deepui_2017\runtimecompiledcplusplus-master\aurora\examples\simpletest\gameobject.cpp: fatal error C1041: cannot open program database 'C:\DeepUI_2017\RuntimeCompiledCPlusPlus-master\Aurora\x64\Debug\vc140.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS


[RuntimeCompiler] Complete

Failed to load module C:\Users\Naeron\AppData\Local\Temp\728B.tmp

```

**Comment by dougbinks** [comment]
Many thanks - following this I'm now able to reproduce the problem and can work on a solution.

It appears that Visual Studio is changing the output somehow after encountering an exception. I'll be in touch once I have a solution.

**Comment by dougbinks** [comment]
Hopefully this commit will fix the issue for you.

Sadly I've had to drop /DEBUG:FASTLINK as well as forcing the pdb name, as without this Visual Studio would read the object file and prevent it from being written to on the next compile.

**Comment by dougbinks** [comment]
Many thanks for helping out with this by the way!

**Comment by Naeron1984** [comment]
Thank YOU! Great support!
Looked up /DEBUG:FASTLINK and the 2X speedup that it promises for linking is nothing compared to the speedup of not having to restart the program at all in most cases. 
(https://blogs.msdn.microsoft.com/vcblog/2014/11/12/speeding-up-the-incremental-developer-build-scenario/)
Also, the linking is just part of the compilation process. So I suspect the major part of it timewise is the object generation so maybe it's not such a great loss anyway. I haven't measured it though.

**Comment by dougbinks** [comment]
Note that you can still use /DEBUG:FASTLINK in your main program, it's just no longer used by the runtime compiler.

**Comment by dtmoodie** [comment]
This fixed my issues as well, thanks so much!

**Comment by ghost** [comment]
for anyone who's Googling this, i had to tell windows defender to ignore my build folder, durr
