### ISSUE TITLE
Failing to generate Codeblocks makefiles

### ISSUE THREAD

**Issue by Vm900** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#93]
Hi
Been trying all week but i keep getting this error:
![cmakeconferror](https://user-images.githubusercontent.com/9399631/27160548-fb4bd51e-516c-11e7-899f-8b63035ba79c.PNG)

Help
Thanks

**Comment by Vm900** [comment]
Tried it again in vs2010 and i get
10 succeded i failed
![vs10compilererror](https://user-images.githubusercontent.com/9399631/27187941-78090884-51e4-11e7-9823-79663d7a2671.PNG)

**Comment by dougbinks** [comment]
There are two unrelated issues here.

In the first case you're trying to use cmake to generate a codeblocks MinGW build. [MinGW isn't supported, and though someone made a MinGW port I do not know if it's currently working](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/issues/60) and I don't know if the codeblocks project will be correctly generated by cmake.

In the second case you need to set the Startup Project to an executable, either the SimpleTest or ConsoleExample project. This is done by right clicking on the project in the Solution Explorer and selecting "Set as StartUp Project".

**Comment by Vm900** [comment]
@dougbinks Thanks
