### ISSUE TITLE
unresolved external symbols  VS2017 RuntimeObjectSystem

### ISSUE THREAD

**Issue by 1JQ** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#99]
Always after compiling project with that code:
`IRuntimeObjectSystem* rOS;
rOS=new RuntimeObjectSystem;
`
 I am getting 1 unresolved external symbol:

error LNK2001: unresolved external symbol "public: __cdecl RuntimeObjectSystem::RuntimeObjectSystem(void)" (??0RuntimeObjectSystem@@QEAA@XZ

**Comment by dougbinks** [comment]
I note you closed and re-opened this issue - have you resolved it?

If not, it looks like you're using Visual Studio from the error message. Is this when compiling the project from within Visual Studio or when running the program and using runtime compilation? The later is expert usage and I would avoid doing so.

The error is a linker error, if you look at the example Aurora_VS2010.sln you will see there are [RuntimeCompiler_VS2010 and RuntimeObjectSystem projects which you will need to include in your project](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/wiki/Integrating-to-your-own-codebase).

**Comment by 1JQ** [comment]
This is while compiling project. I re-opened this issue because I did not see one letter before and I though this was issue. And I have  RuntimeCompiler_VS2010 and RuntimeObjectSystem in my project

**Comment by dougbinks** [comment]
This is a link dependency issue, Normally Visual Studio links project dependencies. You can set the project dependencies under Project->Project Dependencies.

You can also set linker inputs directly. To do this you need to right click on the your main project and select properties then Linker->Input->Additional Dependencies. In there you should add:

RuntimeObjectSystem.lib;RuntimeCompiler_VS2010.lib;

Note that the ; is used to separate between each library, and that you need to do this for all configurations and all platforms (you can select All from the drop down list in the project settings before adding the libraries).

**Comment by 1JQ** [comment]
Thanks! Now it works.
